### ISSUE TITLE
DOCS: Update "Making a PyPI-friendly README" for `pyproject.toml`

### ISSUE THREAD

**Issue by EwoutH** [pypa/packaging.python.org#1164] opened 2022-10-28 15:13 UTC
Since using a `pyproject.toml` is now the best practice for specifying project metadata, I was wondering if the [Making a PyPI-friendly README](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/) guide could be updated for how to specify this in a `pyproject.toml` file.

**Comment by chrysle** [comment] 2023-09-28 07:04
Duplicate of #971

**Closed** 2023-09-28 07:05 UTC
Labels: resolution: duplicate
