### ISSUE TITLE
Is there no preferred approach to single-sourcing the project version?

### ISSUE THREAD

**Issue by nchammas** [pypa/packaging.python.org#182] opened 2015-11-09 19:34 UTC
There are [many approaches](https://github.com/pypa/python-packaging-user-guide/blob/0dcf950850644900af322343fc32025ad8994207/source/single_source_version.rst) offered in the current documentation, but no approach seems to be "recommended" or otherwise suggested as the preferred approach to take. For a new developer looking to package their project, this can be confusing.

Looking at a few of the projects I'm familiar with, it seems that approach 3 is common.

> Set the value to a `__version__` global variable in a dedicated module in your project (e.g. version.py), then have setup.py read and exec the value into a variable.

Would it make sense to present this approach as more than just one among many? Or is there really no preferred way to single-source the project version, even for new projects?

**Comment by pfmoore** [comment] 2015-11-09 19:41
Typically any attempt to recommend a preferred solution is met with debate. There really doesn't seem to be a consensus.

FWIW, if I recall the common objection to the approach you mention here is that it doesn't work properly if your project build directory isn't on sys.path (which it may not be in certain situations).

The objections to the other options seem to me to be no stronger (but no weaker either).

**Comment by nchammas** [comment] 2015-11-09 20:01
> FWIW, if I recall the common objection to the approach you mention here is that it doesn't work properly if your project build directory isn't on sys.path (which it may not be in certain situations).

Is that a common occurrence? I'm not trying to start a debate about this now; I just ask as a total newcomer to packaging. :)

I suppose if there really is no consensus, or even no approach that we can offer as "works for most people", then we can close this issue.

**Comment by pfmoore** [comment] 2015-11-09 20:31
I don't know, it's not my objection...

**Comment by qwcode** [comment] 2015-11-09 21:14
It think approach #3 is becoming more common  (I use it now btw), but it's hard for me to say what is globally "more common", w/o doing some kind of analysis of what's being posted to pypi these days.

let's keep this issue open, and maybe #3 can become preferred at some point.

**Comment by pfmoore** [comment] 2015-11-09 22:07
BTW, my explanation of the objection I've seen is wrong (if you exec the file,you don't need it on sys.path).

One real issue is getting encodings right. The ```execfile``` approach is Python 2 only. The ```exec``` version needs an ```open()``` but Python 2 doesn't support supplying an encoding to ```open()```, and the default encoding depends on the user's PC settings. The best approach is only using ASCII in your ```version.py``` and relying on the fact that nobody's going to have a default encoding that isn't ASCII-compatible. But all it takes is a non-ASCII character in a comment and the read gets a decoding error :-(

But it's a corner case, and not likely to affect newcomers (um, unless they don't speak English as their native language, I guess...)

**Comment by dstufft** [comment] 2015-11-09 23:20
You could always just add ``myproject/_version`` which is just a text file, then have:

```python
# myproject/__init__.py
import pkgutil

__version__ = pkgutil.get_data("myproject", "_version").strip()
```

and

```python
# setup.py
import os.path

with open(os.path.join(os.path.dirname(__file__), "myproject", "_version")) as fp:
    version = fp.read().strip()

setup(
    ...
    version = version,
    ...
)

**Comment by dstufft** [comment] 2015-11-09 23:22
Also, ``codecs.open`` is like ``open`` except it supports an encoding parameter and works on 2 and 3.

**Comment by qwcode** [comment] 2015-11-09 23:31
> You could always just add myproject/_version which is just a text file

btw, this is already presented as one of the options... #4

**Comment by Changaco** [comment] 2015-11-26 12:55
Note: #190 proposes changes to the document that would affect this discussion.

**Comment by Changaco** [comment] 2015-11-26 18:59
The problem I have with all the solutions currently listed in the document is that if your project uses Git tags to mark releases, then there isn't a single source of truth anymore: there's the version number in the code and the one in the tags.

**Comment by nchammas** [comment] 2015-11-26 19:39
That's correct, but I think that falls outside of the domain of what the PUG should cover. If you want your single-source version to be in Git, then you're coupling how Python versioning is done to something outside of Python. What about users who use Mercurial or SVN? Should the guide cover those as well?

As far as the PUG is concerned, I think agreeing on the best approach to having a single source for the version *across your Python code* is what we should shoot for. Once we have that, it's easier to make additional recommendations on how to add an additional layer of indirection to source that version from outside of Python.

So to provide an example, say the guide evolves to converge on [option 3](https://github.com/pypa/python-packaging-user-guide/blob/49bf76fd3e03c062ef4f0a444b7e57697462e138/source/single_source_version.rst). From there, it's much easier to add tips on how to source that version in turn from a VCS.

For example:
> Set the value to a `__version__` global variable in a dedicated module in your project (e.g. `version.py`), then have `setup.py` read and `exec` the value into a variable.
> You can set `__version__` automatically by querying your VCS. For example, in Git...

**Comment by xavfernandez** [comment] 2015-11-26 21:13
Why option 3 and not any other one ? :-)
Note also that all these discussions relate to the use of distutils/setuptools as build tool.

**Comment by nchammas** [comment] 2015-11-26 21:52
Per the discussion earlier in this thread, option 3 seems to be the option that new projects are converging on. Do you observe otherwise?

I think PUG serves the community best when it recognizes already-existing conventions, or when it helps nudge the community towards emerging conventions and accelerates their adoption. I don't think anyone here is trying to invent something new and impose it on people by diktat.

Personally, which option we go with is less important to me than the fact that we converge on a single "recommended" option. It's better for users when there are fewer choices on display for implementing such a basic pattern.

**Comment by nchammas** [comment] 2015-11-26 22:04
To expand a bit: The PUG is a guide, not an encyclopedia. Its purpose is to present common advice to users facing common problems, not to document every possible permutation that people have found useful.

At least, that's how I see the PUG. Perhaps I've misunderstood it's purpose though.

**Comment by xavfernandez** [comment] 2015-11-26 22:50
> Per the discussion earlier in this thread, option 3 seems to be the option that new projects are converging on. Do you observe otherwise?

I must admit I usually don't check the version hack used by the library I use but at work we tend to use something similar to pip: https://github.com/pypa/pip/blob/develop/setup.py#L34-L39 so that would be option 1.

**Comment by pfmoore** [comment] 2015-11-26 22:51
@nchammas That sounds pretty much correct.

**Comment by Changaco** [comment] 2015-11-27 13:04
Since #190 has become tangled with this issue I've turned it into the following proposal:

- simplify option 1 (`__version__` in `__init__`) and use the same coding style in option 3 (`__version__` in `__about__`)
- move option 2 (external tools) to the end
- remove options 4 (complicated variant of option 3) and 5 (unreliable use of `pkg_resources`)
- remove option 6 (importing `__version__` from `__init__`) and mention why it's not recommended (in the note of option 1)
- put the VCS tag solution in its own item, because it's not a release tool so it doesn't fit into option 2

**Comment by Changaco** [comment] 2015-11-27 13:12
I've kept both option 1 and option 3 because I can't find a good argument to declare that one is better than the other.

**Comment by Changaco** [comment] 2015-11-27 15:24
In #190 @pfmoore points out that option 1 is less simple and solid because it uses regexps. That could justify dropping it in favour of option 3. Opinions?

**Comment by pfmoore** [comment] 2015-11-27 16:04
No, I was pointing out that your edits omitted the note that the fact that it used regexps is a factor. I don't think there's anything new in the fact that option 1 uses regexps. So -1 on dropping it "because it uses regexps".

Remember that the original question here was "Is there no preferred approach to single-sourcing the project version?" My answer to that is still "No there isn't, sorry". (But for my personal projects, I don't actually care about single-sourcing the version, having it in a couple of places isn't an issue to me).

**Comment by Changaco** [comment] 2015-11-27 16:35
Sorry, I didn't mean to misrepresent what you said. Your comment about the missing note *made me realize* that option 1 is less simple and solid.

**Comment by pfmoore** [comment] 2015-11-27 16:39
No problem

**Comment by Changaco** [comment] 2015-12-03 17:52
Sorry #190 failed to solve this issue, @nchammas.

Considering the reluctance that was expressed to removing options from the page, maybe splitting the options in two sections (e.g. "recommended" and "other") would be a better approach. I won't be the one making that PR though.

**Comment by ionelmc** [comment] 2016-02-15 23:38
As I understood it, but correct me if I'm wrong, the point of not being opinionated is to prevent the inevitable disagreements and bike-shedding. And that's why PPUG don't want to recommend one way to do it.

That being said, I still believe it should be easier for the user to pick something. Currently you'd be inclined to pick something based on ordering - so there's already some implied recommendation there ;-)

I propose to have a list of pros and cons for each option, and then the user can look over those and decide what's important for him. Cause no one has the same needs.

**Comment by ncoghlan** [comment] 2016-09-24 16:50
Belatedly revisiting this, I do agree there's value in offering folks a prescriptive "I don't care about the details, just give me a 'not wrong' approach that covers absolutely everything I need to do".

However, I also think it's problematic for the *PyPA* specifically to publish such a guide, since it's easy for folks to interpret "this is one good approach" as "all other possible approaches are bad" and try to use it as a lever to coerce maintainers of existing projects into changing the way they do things even when there's nothing wrong with their current approach (cf. folks wanting to retroactively apply modern versions of PEP 8 to code bases that predate those updates by many years).

Accordingly, perhaps we could take the expedient route and offer a link at the start of the Packaging & Distribution guide referencing @hynek's walk-through at https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/ ?

That kind of "This is a good, comprehensive, example of doing it right" endorsement is still softer than actually providing such a prescriptive guide directly on packaging.python.org, but still meets the need for a step-by-step introduction that doesn't ask first-time publishers to make any decisions they may not be comfortable making yet.

**Comment by pfmoore** [comment] 2016-09-24 17:38
One minor thing - @hynek's post says "Sorry, no Windows", which in't needed as (as far as I can see) there's basically nothing in the post that's OS-specific.

But that nit aside, I agree with the principle of pointing to articles that we endorse to break the logjam of "we don't want to say anything as it makes it too official".

**Comment by hynek** [comment] 2016-09-24 17:46
If someone can confirm that everything works on Windows as described, I’ll be *more* than delighted to remove it. :)

**Comment by pfmoore** [comment] 2016-09-24 19:14
I haven't run all of the commands, but I have reviewed everything and the only points I'd make are:

1. The ```read()``` function in ```setup.py``` assumes UTF-8. Windows users will have to specifically ensure that they get their text editor to save in UTF-8. But honestly, it's the only sane cross-platform choice, so that's not a problem.
2. In the "You can test whether both install properly" sections, the commands are Unix, but there's no way you could avoid some level of platform specificity in an example like this. I'd just add a comment "the examples use Unix, Windows would be similar".

(Honestly, as a Windows user, I'm used to reading articles on the net that use Unix terms, and mentally translating. I wouldn't even have thought about the issue if you hadn't explicitly mentioned it).

**Comment by iMichka** [comment] 2016-12-11 15:50
Just adding my 2 cents to the discussion. I stumbled over this a few days ago, as I also have 4 places where I need to change the version number in my library, and failed to do so correctly already twice.

I really like method 1, as the ```__version__``` is defined in your main ```__init__.py``` as a string, which I would expect from most packages. It is the first place where I would look for it. If the problem is that regexes are perceived as hard / obscure for some people, why could setuptools not propose the ```find_version``` method ? It really looks like some boilerplate code that could benefit to everybody. That would hide the complexity away from the end user, and allow the setup tools maintainer to take care of the details.

About method 4, I find that saying:
> An advantage with this technique is that it’s not specific to Python. Any tool can read the version

is probably not really an advantage. It's just more direct. You can probably extract that version from a .py file with any other language or tool without too much hassle.

And I think that having 7 options is way too many. Besides, at the end you end up reading this thread to get even more opinions :), which is great but ... not realistic for most of the users.

**Comment by flying-sheep** [comment] 2019-08-02 11:22
None of these is single-source, as pretty much everything is under version control these days, and people tag versions. I prefer using the VCS as source for the version using [`get_version`](https://github.com/flying-sheep/get_version) or [`versioneer`](https://github.com/warner/python-versioneer).

**Comment by ChrisBarker-NOAA** [comment] 2023-07-10 17:26
PIng! This is a really old issue, and a lot of work (including at least two PRs merged has been done -- close it?

Note: there's some work still to be done (things move fast!) on the Single-sourcing the package version page, but that's for another issue or PR.

**Comment by flying-sheep** [comment] 2023-07-11 10:13
[hatch-vcs](https://github.com/ofek/hatch-vcs) is a good solution. To switch to it, one simply has to do

```diff
 [build-system]
 build-backend = "hatchling.build"
 requires = [
   "hatchling",
+  "hatch-vcs",
 ]

 [project]
 ...
-version = "..."
+dynamic = ["version"]

+[tool.hatch.version]
+source = "vcs"
```

**Comment by pfmoore** [comment] 2023-07-11 11:26
I think this issue can be closed. In the end, there will always be multiple approaches, even if only because people don't all agree on *which* source should be the single source.

The packaging guide could do with updating - personally, I'd structure it by starting from "where do you want to hold the single copy of your version?" and discuss options for each of the potential choices from there - but that's separate, and really just needs people to do the work of writing new text, rather than more discussions of what options exist.

> [hatch-vcs](https://github.com/ofek/hatch-vcs) is a good solution.

... if you're using hatch, and you want to use a git tag as your master version 🙂

**Comment by flying-sheep** [comment] 2023-07-11 13:32
I fully agree with everything you said, just wanted to give some practical advice for people stumbling upon this thread.

**Comment by wimglenn** [comment] 2023-07-12 22:22
Can we just _remove_ this page entirely?  It's terribly quaint.

The modern ways are dynamic version, managed from VCS, or just written statically/directly in [`pyproject.toml`](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#version) like:

```
[project]
version = "1.0"
```

Duplication a `__version__` attribute in module namespace has been unnecessary/undesirable since `importlib.metadata` made it to stdlib (Python 3.8), and the [PEP396 rejection notice](https://peps.python.org/pep-0396/#pep-rejection) from 2021 says similar:

> The packaging ecosystem has changed significantly in the intervening years since this PEP was first written, and APIs such as [`importlib.metadata.version()`](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) provide for a much better experience.

The whole page seems like a hangover from distutils days and we'd be in a better place just removing these outdated approaches.

**Comment by ChrisBarker-NOAA** [comment] 2023-07-12 23:19
> The whole page seems like a hangover from distutils days and 

Well, yes, which is why I did WIP PR #1273  -- in that PR I didn't actually remove anything, but it may be time to do that.

> we'd be in a better place just removing such outdated advice.

I take issue with some of this -- despite the SC's ruling on PEP396, I really like __version__, and it absolutely can be done with single source, as recommend, and as setuptools will do for you.

NOTE: PEP 396 was complicated by ideas about putting __Version__ in the standard library -- I still think it's excellent advise for third party packages: KISS

That's a debate for somewhere else -- in this thread, we've specifically said that these docs are not going to bless any particular method.

**Comment by hynek** [comment] 2023-07-13 04:47
JFTR, you can have it both ways: https://github.com/hynek/stamina/blob/main/src/stamina/__init__.py

Simply add this to your `__init__.py`:

```python
def __getattr__(name: str) -> str:
    if name != "__version__":
        msg = f"module {__name__} has no attribute {name}"
        raise AttributeError(msg)

    from importlib.metadata import metadata

    return metadata("YOUR-PKG")["version"]
```

I used to raise a deprecation warning but turns out users really like `__version__`.

**Comment by ChrisBarker-NOAA** [comment] 2023-07-13 06:00
Exactly -- MTOWTDI  -- which is the point of this thread -- no definitive recommendation.

The question is what the Docs should say -- let's have that discussion in the PR.

**Comment by flying-sheep** [comment] 2023-07-13 08:39
> turns out users really like `__version__`.

I’m not sure that’s a good reason to keep it.

`importlib.metadata.version('distname')` is the standardized way to do this and always works, while `__version__` is just a convention.

**Comment by hynek** [comment] 2023-07-13 09:05
see https://github.com/python-attrs/attrs/issues/1136 for the concrete issue. As far as I understand, it's impossible to reason from an imported module to the package that installed it (happy to be corrected tho). And looks like pydoc looks at `__version__` too.

**Comment by flying-sheep** [comment] 2023-07-13 10:56
> it's impossible to reason from an imported module to the package that installed it

[`importlib.metadata.packages_distributions()`](https://docs.python.org/3/library/importlib.metadata.html#mapping-import-to-distribution-packages) gives you a mapping.

**Comment by wimglenn** [comment] 2023-07-13 18:44
@hynek  Is there a reason why you went with `importlib.metadata.metadata("stamina")["version"]` instead of `importlib.metadata.version("stamina")`?

**Comment by hynek** [comment] 2023-07-13 19:35
Three theories:

1. Copy paste.
2. It's the first I found and it was good enough.
3. In legacy projects I mapped all the data and it was easier to map dunders like this (see eg attrs)

**Comment by wimglenn** [comment] 2023-07-20 05:19
I offer https://github.com/pypa/packaging.python.org/pull/1276 as an alternative to https://github.com/pypa/packaging.python.org/pull/1273.

**Comment by sinoroc** [comment] 2023-07-22 19:49
I feel like it is a matter of what we the scope of `packaging.pythong.org` to be. From one of the latest `discuss.python.org` (a few months ago alread), I was under the impression that the direction was towards minimizing the scope as much as possible to focus mostly on the packaging specifications and the things that are part of Python and its standard library.

So in this case, I guess it would be enough to mention `importlib.metadata.version()` and how to use it. The other techniques such as those involving build back-ends plugins would be out of scope. We could mention that those exist but without naming them in particular. If we name them then we have to ensure over time that these techniques and plugins still exist and are still up-to-date with the latest specifications, otherwise we are misleading users.

**Comment by wimglenn** [comment] 2023-07-23 00:18
Right, the approaches shown in #1273 would be more at home in the setuptools docs. They're features quite specific to a setuptools-based build backend. The [_Python Packaging User Guide_](packaging.python.org) should strive not to be so closely wedded to setuptools.

**Comment by sinoroc** [comment] 2023-07-23 16:22
I also wonder about the possible confusion between distribution package and import package. Should `import something; print(something.__version__)` always report the same value as `importlib.metadata; print(importlib.metadata.version('Something'))`.

Even in the cases where both are strictly the same (and importing the package is not too costly in terms of resources), aren't we being misleading by recommending to obtain the version string from the import package instead of from the installed distribution package metadata.

**Comment by webknjaz** [comment] 2023-09-06 20:32
> I offer #1276 as an alternative

FTR I commented on this one if anybody from this thread wants to take a look.

**Comment by ncoghlan** [comment] 2024-10-15 12:05
#1612 resolves this by explaining that `pkg.__version__` and `importlib.metadata.version("pkg")` are reporting the version of two *different* things (an import package or module and a distribution package) that happen to share a name.

The old setuptools-specific guide is now just a HTTP redirect to the discussion page that mostly defers to "consult the documentation of your chosen build system".

**Closed by ncoghlan** 2024-10-15 12:05 UTC
Labels: type: question

**Comment by ChrisBarker-NOAA** [comment] 2024-10-15 18:22
> two different things (an import package or module and a distribution package) that happen to share a name

They may *not* have the same name -- one reason why both are useful. 

I'll take another look at #1612 and see if there's anymore clarification needed there.
